create extension if not exists pgcrypto;

do $$ begin
  create type public.group_role as enum ('admin', 'editor', 'musician');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(trim(name)) between 2 and 80),
  invite_code text not null unique default upper(substr(encode(gen_random_bytes(8), 'hex'), 1, 8)),
  owner_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.group_members (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.group_role not null default 'musician',
  created_at timestamptz not null default now(),
  primary key (group_id, user_id)
);

create table if not exists public.songs (
  id text primary key,
  group_id uuid not null references public.groups(id) on delete cascade,
  title text not null check (char_length(trim(title)) between 1 and 160),
  artist text not null check (char_length(trim(artist)) between 1 and 160),
  original_key text not null,
  song_key text not null,
  tempo integer not null check (tempo between 30 and 240),
  time_signature text not null check (time_signature ~ '^[0-9]+/[0-9]+$'),
  tags text[] not null default '{}',
  notes text not null default '',
  chord_pro text not null check (char_length(trim(chord_pro)) > 0),
  duration_seconds integer not null default 180 check (duration_seconds >= 0),
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

create table if not exists public.setlists (
  id text primary key,
  group_id uuid not null references public.groups(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 160),
  event_date date not null,
  notes text not null default '',
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.setlist_songs (
  id bigint generated by default as identity primary key,
  setlist_id text not null references public.setlists(id) on delete cascade,
  song_id text not null references public.songs(id) on delete cascade,
  position integer not null check (position >= 0),
  performance_key text,
  notes text not null default '',
  unique (setlist_id, song_id),
  unique (setlist_id, position)
);

create index if not exists group_members_user_id_idx on public.group_members (user_id);
create index if not exists songs_group_id_idx on public.songs (group_id);
create index if not exists setlists_group_id_idx on public.setlists (group_id);
create index if not exists setlist_songs_setlist_id_idx on public.setlist_songs (setlist_id);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists groups_touch_updated_at on public.groups;
create trigger groups_touch_updated_at before update on public.groups
for each row execute function public.touch_updated_at();

drop trigger if exists songs_touch_updated_at on public.songs;
create trigger songs_touch_updated_at before update on public.songs
for each row execute function public.touch_updated_at();

drop trigger if exists setlists_touch_updated_at on public.setlists;
create trigger setlists_touch_updated_at before update on public.setlists
for each row execute function public.touch_updated_at();

create or replace function public.is_group_member(target_group_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.group_members gm
    where gm.group_id = target_group_id
      and gm.user_id = auth.uid()
  );
$$;

create or replace function public.has_group_role(target_group_id uuid, allowed_roles public.group_role[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.group_members gm
    where gm.group_id = target_group_id
      and gm.user_id = auth.uid()
      and gm.role = any(allowed_roles)
  );
$$;

create or replace function public.ensure_default_group(group_name text default 'ViveSong')
returns table (group_id uuid, role public.group_role, invite_code text)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Not authenticated';
  end if;

  return query
  select gm.group_id, gm.role, g.invite_code
  from public.group_members gm
  join public.groups g on g.id = gm.group_id
  where gm.user_id = current_user_id
  order by gm.created_at asc
  limit 1;

  if found then
    return;
  end if;

  insert into public.groups (name, owner_id)
  values (coalesce(nullif(trim(group_name), ''), 'ViveSong'), current_user_id)
  returning id, groups.invite_code into group_id, invite_code;

  insert into public.group_members (group_id, user_id, role)
  values (group_id, current_user_id, 'admin');

  role := 'admin';
  return next;
end;
$$;

create or replace function public.join_group_by_code(code text)
returns table (group_id uuid, role public.group_role, invite_code text)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  target_group_id uuid;
begin
  if current_user_id is null then
    raise exception 'Not authenticated';
  end if;

  select g.id into target_group_id
  from public.groups g
  where upper(g.invite_code) = upper(trim(code));

  if target_group_id is null then
    raise exception 'Invalid invite code';
  end if;

  insert into public.group_members (group_id, user_id, role)
  values (target_group_id, current_user_id, 'musician')
  on conflict (group_id, user_id) do nothing;

  return query
  select gm.group_id, gm.role, g.invite_code
  from public.group_members gm
  join public.groups g on g.id = gm.group_id
  where gm.group_id = target_group_id
    and gm.user_id = current_user_id;
end;
$$;

alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.songs enable row level security;
alter table public.setlists enable row level security;
alter table public.setlist_songs enable row level security;

drop policy if exists "members can read their groups" on public.groups;
create policy "members can read their groups" on public.groups
for select using (public.is_group_member(id));

drop policy if exists "admins can update their groups" on public.groups;
create policy "admins can update their groups" on public.groups
for update using (public.has_group_role(id, array['admin']::public.group_role[]))
with check (public.has_group_role(id, array['admin']::public.group_role[]));

drop policy if exists "members can read memberships" on public.group_members;
create policy "members can read memberships" on public.group_members
for select using (public.is_group_member(group_id));

drop policy if exists "admins can manage memberships" on public.group_members;
create policy "admins can manage memberships" on public.group_members
for all using (public.has_group_role(group_id, array['admin']::public.group_role[]))
with check (public.has_group_role(group_id, array['admin']::public.group_role[]));

drop policy if exists "members can read songs" on public.songs;
create policy "members can read songs" on public.songs
for select using (public.is_group_member(group_id));

drop policy if exists "editors can insert songs" on public.songs;
create policy "editors can insert songs" on public.songs
for insert with check (
  created_by = auth.uid()
  and public.has_group_role(group_id, array['admin','editor']::public.group_role[])
);

drop policy if exists "editors can update songs" on public.songs;
create policy "editors can update songs" on public.songs
for update using (public.has_group_role(group_id, array['admin','editor']::public.group_role[]))
with check (public.has_group_role(group_id, array['admin','editor']::public.group_role[]));

drop policy if exists "admins can delete songs" on public.songs;
create policy "admins can delete songs" on public.songs
for delete using (public.has_group_role(group_id, array['admin']::public.group_role[]));

drop policy if exists "members can read setlists" on public.setlists;
create policy "members can read setlists" on public.setlists
for select using (public.is_group_member(group_id));

drop policy if exists "editors can insert setlists" on public.setlists;
create policy "editors can insert setlists" on public.setlists
for insert with check (
  created_by = auth.uid()
  and public.has_group_role(group_id, array['admin','editor']::public.group_role[])
);

drop policy if exists "editors can update setlists" on public.setlists;
create policy "editors can update setlists" on public.setlists
for update using (public.has_group_role(group_id, array['admin','editor']::public.group_role[]))
with check (public.has_group_role(group_id, array['admin','editor']::public.group_role[]));

drop policy if exists "admins can delete setlists" on public.setlists;
create policy "admins can delete setlists" on public.setlists
for delete using (public.has_group_role(group_id, array['admin']::public.group_role[]));

drop policy if exists "members can read setlist songs" on public.setlist_songs;
create policy "members can read setlist songs" on public.setlist_songs
for select using (
  exists (
    select 1 from public.setlists s
    where s.id = setlist_songs.setlist_id
      and public.is_group_member(s.group_id)
  )
);

drop policy if exists "editors can manage setlist songs" on public.setlist_songs;
create policy "editors can manage setlist songs" on public.setlist_songs
for all using (
  exists (
    select 1 from public.setlists s
    where s.id = setlist_songs.setlist_id
      and public.has_group_role(s.group_id, array['admin','editor']::public.group_role[])
  )
)
with check (
  exists (
    select 1 from public.setlists s
    join public.songs so on so.id = setlist_songs.song_id and so.group_id = s.group_id
    where s.id = setlist_songs.setlist_id
      and public.has_group_role(s.group_id, array['admin','editor']::public.group_role[])
  )
);

grant usage on schema public to authenticated;

grant select, insert, update, delete on public.groups to authenticated;
grant select, insert, update, delete on public.group_members to authenticated;
grant select, insert, update, delete on public.songs to authenticated;
grant select, insert, update, delete on public.setlists to authenticated;
grant select, insert, update, delete on public.setlist_songs to authenticated;

grant usage, select on all sequences in schema public to authenticated;

grant execute on function public.ensure_default_group(text) to authenticated;
grant execute on function public.join_group_by_code(text) to authenticated;
grant execute on function public.is_group_member(uuid) to authenticated;
grant execute on function public.has_group_role(uuid, public.group_role[]) to authenticated;
